#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on the machine

# Use ip command to get network interfaces and extract IPv4 addresses
ip addr show | grep -E 'inet [0-9]' | awk '{print $2}' | cut -d'/' -f1
